version: '2'
services:
  lint-test-extract-log:
    build:
      context: .
      dockerfile: Dockerfile-lint-test
    command:
      - bash
      - '-c'
      - 'rustfmt src/**.rs --write-mode=diff && cargo clippy && cargo test'
